In [1]:
import pandas as pd

In [37]:
df = pd.read_csv('pokemon.csv')
df = df.iloc[:, :24]
df = df.drop(columns=['german_name', 'japanese_name', 'type_number', 'type_2'])
df = df.rename(columns={'Unnamed: 0': 'csv_index'})
df = df.set_index('csv_index')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1045 entries, 0 to 1044
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   pokedex_number    1045 non-null   int64
 1   name              1045 non-null   object
 2   generation        1045 non-null   int64
 3   status            1045 non-null   object
 4   species           1045 non-null   object
 5   type_1            1045 non-null   object
 6   height_m          1045 non-null   float64
 7   weight_kg         1044 non-null   float64
 8   abilities_number  1045 non-null   int64
 9   ability_1         1042 non-null   object
 10  ability_2         516 non-null    object
 11  ability_hidden    813 non-null    object
 12  total_points      1045 non-null   int64
 13  hp                1045 non-null   int64
 14  attack            1045 non-null   int64
 15  defense           1045 non-null   int64
 16  sp_attack         1045 non-null   int64
 17  sp_defense        1045 non-null   int64
 18  speed             1045 non-null   int64
dtypes: float64(2), int64(10), object(7)
memory usage: 163.3+ KB

In [39]:
duplicates = df[df['pokedex_number'].duplicated(keep=False)]
duplicates

,pokedex_number,name,generation,status,species,type_1,height_m,weight_kg,abilities_number,ability_1,ability_2,ability_hidden,total_points,hp,attack,defense,sp_attack,sp_defense,speed
csv_index,,,,,,,,,,,,,,,,,,,
2,3,Venusaur,1,Normal,Seed Pokémon,Grass,2.0,100.0,2,Overgrow,NaN,Chlorophyll,525,80,82,83,100,100,80
3,3,Mega Venusaur,1,Normal,Seed Pokémon,Grass,2.4,155.5,1,Thick Fat,NaN,NaN,625,80,100,123,122,120,80
6,6,Charizard,1,Normal,Flame Pokémon,Fire,1.7,90.5,2,Blaze,NaN,Solar Power,534,78,84,78,109,85,100
7,6,Mega Charizard X,1,Normal,Flame Pokémon,Fire,1.7,110.5,1,Tough Claws,NaN,NaN,634,78,130,111,130,85,100
8,6,Mega Charizard Y,1,Normal,Flame Pokémon,Fire,1.7,100.5,1,Drought,NaN,NaN,634,78,104,78,159,115,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,892,Urshifu Single Strike Style,8,Sub Legendary,Wushu Pokémon,Fighting,1.9,105.0,1,Unseen Fist,NaN,NaN,550,100,130,100,63,60,97
1036,892,Urshifu Rapid Strike Style,8,Sub Legendary,Wushu Pokémon,Fighting,1.9,105.0,1,Unseen Fist,NaN,NaN,550,100,130,100,63,60,97
1042,898,Calyrex,8,Legendary,King Pokémon,Psychic,1.1,7.7,1,Unnerve,NaN,NaN,500,100,80,80,80,80,80
1043,898,Calyrex Ice Rider,8,Legendary,High King Pokémon,Psychic,2.4,809.1,1,As One,NaN,NaN,680,100,165,150,85,130,50
1044,898,Calyrex Shadow Rider,8,Legendary,High King Pokémon,Psychic,2.4,53.6,1,As One,NaN,NaN,680,100,85,80,165,100,150

In [40]:
duplicates['dup_count'] = duplicates.groupby('pokedex_number').cumcount()

C:\Users\amege\AppData\Local\Temp\ipykernel_7976\2421047973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates['dup_count'] = duplicates.groupby('pokedex_number').cumcount()

In [42]:
duplicates[['pokedex_number', 'name', 'dup_count']]

           pokedex_number                         name  dup_count
csv_index
2                       3                     Venusaur          0
3                       3                Mega Venusaur          1
6                       6                    Charizard          0
7                       6             Mega Charizard X          1
8                       6             Mega Charizard Y          2
...                   ...                          ...        ...
1035                  892  Urshifu Single Strike Style          0
1036                  892   Urshifu Rapid Strike Style          1
1042                  898                      Calyrex          0
1043                  898            Calyrex Ice Rider          1
1044                  898         Calyrex Shadow Rider          2

[267 rows x 3 columns]

In [46]:
duplicates['new_pokedex'] = duplicates.apply(
    lambda row: f"{str(row['pokedex_number']).zfill(3)}_f{row['dup_count']+1}" if row['dup_count'] > 0 else str(row['pokedex_number']).zfill(3),
    axis=1
)
duplicates[['pokedex_number', 'name', 'dup_count', 'new_pokedex']]

C:\Users\amege\AppData\Local\Temp\ipykernel_7976\3022470026.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates['new_pokedex'] = duplicates.apply(

           pokedex_number                         name  dup_count new_pokedex
csv_index
2                       3                     Venusaur          0         003
3                       3                Mega Venusaur          1      003_f2
6                       6                    Charizard          0         006
7                       6             Mega Charizard X          1      006_f2
8                       6             Mega Charizard Y          2      006_f3
...                   ...                          ...        ...         ...
1035                  892  Urshifu Single Strike Style          0         892
1036                  892   Urshifu Rapid Strike Style          1      892_f2
1042                  898                      Calyrex          0         898
1043                  898            Calyrex Ice Rider          1      898_f2
1044                  898         Calyrex Shadow Rider          2      898_f3

[267 rows x 4 columns]